#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Load nvm and switch to the version declared in .nvmrc
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm use >/dev/null 2>&1

pnpm pre-commit
